{{- if .Values.database.enabled }}
{{- if not .Values.database.existingSecret }}
{{- /* Generate or preserve password */ -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-db-credentials" (include "keycloak.fullname" .)) -}}
{{- $defaultPassword := "" -}}
{{- if $existingSecret -}}
  {{- $defaultPassword = index $existingSecret.data "password" | b64dec -}}
{{- else -}}
  {{- $defaultPassword = randAlphaNum 32 -}}
{{- end -}}
{{- $finalPassword := .Values.database.password | default $defaultPassword -}}
---
# Secret for Keycloak deployment to read (in release namespace)
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-db-credentials
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.database.username | quote }}
  password: {{ $finalPassword | quote }}
{{- end }}
{{- end }}
