{{- if .Values.mcpServer.oidcClient.enabled }}
---
# Job to create OIDC client for MCP server in Keycloak
# Runs post-install and post-upgrade, idempotent (checks if client exists)
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "keycloak.fullname" . }}-oidc-client
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: oidc-client-setup
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 10
  template:
    metadata:
      labels:
        {{- include "keycloak.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: oidc-client-setup
    spec:
      restartPolicy: OnFailure
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: shared-data
        emptyDir: {}
      initContainers:
      - name: get-oidc-credentials
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - sh
        - -c
        - |
          set -e
          echo "Setting up OIDC client for MCP server..."

          # Wait for Keycloak and authenticate
          echo "Waiting for Keycloak to be ready and authenticating..."
          MAX_ATTEMPTS=60
          ATTEMPT=0
          until /opt/keycloak/bin/kcadm.sh config credentials \
            --server http://{{ include "keycloak.fullname" . }}:{{ .Values.service.port }} \
            --realm {{ .Values.mcpServer.oidcClient.realm }} \
            --user "$KEYCLOAK_ADMIN" \
            --password "$KEYCLOAK_ADMIN_PASSWORD" 2>&1; do
            ATTEMPT=$((ATTEMPT+1))
            if [ $ATTEMPT -ge $MAX_ATTEMPTS ]; then
              echo "ERROR: Keycloak did not become ready after $MAX_ATTEMPTS attempts"
              exit 1
            fi
            echo "Attempt $ATTEMPT/$MAX_ATTEMPTS: Keycloak not ready yet, waiting 10s..."
            sleep 10
          done

          echo "Keycloak is ready and authenticated successfully"

          # Check if client already exists
          CLIENT_ID="{{ .Values.mcpServer.oidcClient.clientId }}"
          echo "Checking if client '$CLIENT_ID' exists..."

          if /opt/keycloak/bin/kcadm.sh get clients -r {{ .Values.mcpServer.oidcClient.realm }} --fields clientId 2>/dev/null | grep -q "\"$CLIENT_ID\""; then
            echo "Client '$CLIENT_ID' already exists"

            # Get client UUID
            CLIENT_UUID=$(/opt/keycloak/bin/kcadm.sh get clients -r {{ .Values.mcpServer.oidcClient.realm }} -q clientId="$CLIENT_ID" --fields id 2>/dev/null | grep -o '"id" : "[^"]*"' | cut -d'"' -f4)
            echo "Client UUID: $CLIENT_UUID"
          else
            echo "Creating OIDC client '$CLIENT_ID'..."

            {{- $firstHost := index .Values.ingress.hosts 0 }}
            {{- $hostname := $firstHost.host }}

            # Create client
            CLIENT_UUID=$(/opt/keycloak/bin/kcadm.sh create clients -r {{ .Values.mcpServer.oidcClient.realm }} \
              -s clientId="$CLIENT_ID" \
              -s "name={{ .Values.mcpServer.oidcClient.name }}" \
              -s "description={{ .Values.mcpServer.oidcClient.description }}" \
              -s enabled=true \
              -s clientAuthenticatorType=client-secret \
              -s "redirectUris=[\"https://{{ $hostname }}{{ .Values.mcpServer.path }}/*\"]" \
              -s "webOrigins=[\"https://{{ $hostname }}\"]" \
              -s publicClient=false \
              -s directAccessGrantsEnabled={{ .Values.mcpServer.oidcClient.directAccessGrants }} \
              -s standardFlowEnabled={{ .Values.mcpServer.oidcClient.standardFlow }} \
              -s serviceAccountsEnabled={{ .Values.mcpServer.oidcClient.serviceAccounts }} \
              -s authorizationServicesEnabled={{ .Values.mcpServer.oidcClient.authorization }} \
              -i 2>/dev/null)

            echo "Client created successfully"
            echo "Client UUID: $CLIENT_UUID"
          fi

          # Get client secret
          echo "Retrieving client secret..."
          CLIENT_SECRET=$(/opt/keycloak/bin/kcadm.sh get "clients/$CLIENT_UUID/client-secret" -r {{ .Values.mcpServer.oidcClient.realm }} 2>/dev/null | grep -o '"value" : "[^"]*"' | cut -d'"' -f4)

          if [ -z "$CLIENT_SECRET" ]; then
            echo "ERROR: Failed to retrieve client secret"
            exit 1
          fi

          echo "Client secret retrieved successfully"

          # Write credentials to shared volume for kubectl container
          echo "$CLIENT_ID" > /shared/client-id
          echo "$CLIENT_SECRET" > /shared/client-secret

          echo "Credentials written to shared volume"
        volumeMounts:
        - name: shared-data
          mountPath: /shared
        env:
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.admin.existingSecret | default (printf "%s-admin" (include "keycloak.fullname" .)) }}
              key: username
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.admin.existingSecret | default (printf "%s-admin" (include "keycloak.fullname" .)) }}
              key: password
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
      containers:
      - name: create-k8s-secret
        image: bitnami/kubectl:latest
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - |
          set -e
          echo "Creating Kubernetes secret with OIDC credentials..."

          # Read credentials from shared volume
          CLIENT_ID=$(cat /shared/client-id)
          CLIENT_SECRET=$(cat /shared/client-secret)

          # Create secret using kubectl
          kubectl create secret generic {{ include "keycloak.fullname" . }}-mcp-client \
            --from-literal=client-id="$CLIENT_ID" \
            --from-literal=client-secret="$CLIENT_SECRET" \
            --namespace={{ .Release.Namespace }} \
            --dry-run=client -o yaml | kubectl apply -f -

          # Add labels
          kubectl label secret {{ include "keycloak.fullname" . }}-mcp-client \
            app.kubernetes.io/name={{ include "keycloak.name" . }} \
            app.kubernetes.io/instance={{ .Release.Name }} \
            app.kubernetes.io/managed-by={{ .Release.Service }} \
            --namespace={{ .Release.Namespace }} \
            --overwrite

          echo "OIDC client setup complete!"
          echo "Client ID: $CLIENT_ID"
          echo "Client secret stored in secret: {{ include "keycloak.fullname" . }}-mcp-client"
        volumeMounts:
        - name: shared-data
          mountPath: /shared
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
      serviceAccountName: {{ include "keycloak.fullname" . }}-oidc-setup
{{- end }}
