apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-mcp-auth
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.mcpServer.auth.username | quote }}
  password: {{ .Values.mcpServer.auth.password | default (randAlphaNum 32) | quote }}
  # Generate htpasswd format for nginx basic auth
  auth: {{ htpasswd .Values.mcpServer.auth.username (.Values.mcpServer.auth.password | default (randAlphaNum 32)) | quote }}
