{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-mcp-auth" (include "keycloak.fullname" .)) -}}
{{- $defaultPassword := "" -}}
{{- if $existingSecret -}}
  {{- $defaultPassword = index $existingSecret.data "password" | b64dec -}}
{{- else -}}
  {{- $defaultPassword = randAlphaNum 32 -}}
{{- end -}}
{{- $password := .Values.mcpServer.auth.password | default $defaultPassword -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-mcp-auth
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.mcpServer.auth.username | quote }}
  password: {{ $password | quote }}
  # Generate htpasswd format for nginx basic auth
  auth: {{ htpasswd .Values.mcpServer.auth.username $password | quote }}
