{{- if not .Values.admin.existingSecret }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-admin" (include "keycloak.fullname" .)) -}}
{{- $defaultPassword := "" -}}
{{- if $existingSecret -}}
  {{- $defaultPassword = index $existingSecret.data "password" | b64dec -}}
{{- else -}}
  {{- $defaultPassword = randAlphaNum 32 -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-admin
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.admin.username | quote }}
  password: {{ .Values.admin.password | default $defaultPassword | quote }}
{{- end }}
